#!/bin/sh


/bin/echo /sbin/mdev > /proc/sys/kernel/hotplug
/sbin/mdev -s
# Start all init scripts in /etc/init.d
# executing them in numerical order.
#
for i in /etc/init.d/S??* ;do

     # Ignore dangling symlinks (if any).
     [ ! -f "$i" ] && continue

     case "$i" in
	*.sh)
	    # Source shell script for speed.
	    (
		trap - INT QUIT TSTP
		set start
		. $i
	    )
	    ;;
	*)
	    # No sh extension, so fork subprocess.
	    $i start
	    ;;
    esac
done
/sbin/ifconfig eth0 up
/sbin/udhcpc &
/usr/sbin/ubiattach /dev/ubi_ctrl -m 7 -d 1
/bin/mount -t ubifs ubi1:data /mnt/data
cd /mnt/data
/mnt/data/watch_3g > /dev/null  &
/mnt/data/watch_nic &
/etc/init.d/loragw start
/etc/init.d/synctime &
/usr/sbin/crond -c /root

